name: ezTrack
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=21.1.0=py36h8f6f2f9_0
  - async_generator=1.10=pyhd8ed1ab_1
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - blas=1.1=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - bokeh=2.1.1=py36h9f0ad1d_0
  - brotlipy=0.7.0=py36h8f6f2f9_1001
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.4=py36h211aa47_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=35.0.0=py36hb60f036_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.16.2=h5bd4931_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.14.2=h14ed4e7_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.3=hba1933b_1001
  - holoviews=1.13.5=pyh9f0ad1d_0
  - icu=58.2=hf484d3e_1000
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=4.8.1=py36h5fab9bb_0
  - ipykernel=5.5.5=py36hcb3619a_0
  - ipython=7.16.1=py36he448a4c_2
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - ipywidgets=7.7.4=pyhd8ed1ab_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.2=py36h5fab9bb_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py36h5fab9bb_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py36h605e78d_1
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.44=h1423503_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=13_linux64_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libopenblas=0.3.18=hf726d26_0
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=0.5.2=7
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.9.9=h13577e0_2
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py36h8f6f2f9_0
  - matplotlib=3.1.1=py36_0
  - matplotlib-base=3.1.1=py36hfd891ef_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - nbclient=0.5.9=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36h5fab9bb_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.3=0
  - notebook=6.3.0=py36h5fab9bb_0
  - numpy=1.19.5=py36hfc0c790_2
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.2.20=8
  - opencv=3.4.3=py36_blas_openblash1006a3a_201
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1w=hd590300_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=0.23.0=py36_1
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.9.7=py_0
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.7.1=pyh9f0ad1d_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py36h4f9996e_1
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.34.0=h14c3975_1003
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pyrsistent=0.17.3=py36h8f6f2f9_2
  - pysocks=1.7.1=py36h5fab9bb_3
  - python=3.6.11=h4d41432_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyviz_comms=3.0.3=pyhd8ed1ab_0
  - pyyaml=5.4.1=py36h8f6f2f9_1
  - pyzmq=22.3.0=py36h7068817_0
  - qt=5.6.3=h8bf5577_3
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.0.1=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - requests=2.28.1=pyhd8ed1ab_0
  - scipy=1.2.1=py36h09a28d5_1
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=58.0.4=py36h5fab9bb_2
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.0=h6d4b2fc_0
  - terminado=0.12.1=py36h5fab9bb_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.1=py36h8f6f2f9_1
  - tqdm=4.65.0=pyhd8ed1ab_0
  - traitlets=4.3.3=pyhd8ed1ab_2
  - typing_extensions=4.1.1=pyha770c72_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - jupyter-console==6.4.3
      - lab==7.1
      - simplejson==3.20.1
      - txt2tags==3.7
prefix: /home/corvus/anaconda3/envs/ezTrack
